version: '3.8'  # Use the version of Docker Compose you're working with

services:
  app:
    build: .
    ports:
      - "8501:8501"  # Map container port 8501 to host port 8501
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app  # Mount the current directory to /app in the container for live updates
    command: ["streamlit", "run", "app.py"]

# Optional: Define other services or configurations as needed
